language: java
jdk:
  - openjdk8

services:
  - postgresql

addons:
  sonarcloud:
    organization: "rondoublec"
#    token:
#      secure: "1ad579afa992a0a2494f932549fb215381922f6c"

before_script:
#  - psql -c "CREATE USER usr_elit WITH PASSWORD 'elit';" -U postgres
#  - psql -c "CREATE DATABASE bdd_elit;" -U postgres
#  - psql -c "GRANT ALL PRIVILEGES ON DATABASE bdd_elit to usr_elit;" -U postgres
#  - psql -U usr_elit -d bdd_elit -a -f init_bdd_elit_test.sql

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Rondoublec_myerp09 -Dsonar.login=1ad579afa992a0a2494f932549fb215381922f6c -Ptest-integration
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
